on:
  push:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    - run: echo "CONTAINER=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV
    - run: echo "BRANCH_TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV
    - name: docker build
      run: >
        docker build
        --no-cache
        -t $CONTAINER:BRANCH_TAG
        -f Dockerfile .
    - run: docker push $CONTAINER --all-tags
